# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c6e0447e2778dcda94575592df48bb99"
name = "box-shipping-calculator"
handle = "box-shipping-calculator"
application_url = "https://chicago-illinois-acrylic-groups.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_shipping,write_shipping,read_products,write_products,read_orders"

[auth]
redirect_urls = ["https://chicago-illinois-acrylic-groups.trycloudflare.com/auth/callback", "https://chicago-illinois-acrylic-groups.trycloudflare.com/auth/shopify/callback", "https://chicago-illinois-acrylic-groups.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
