# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "420046e9e72ecb9790d6749bd5114f26"
name = "box-shipping-calculator"
handle = "box-shipping-calculator-2"
application_url = "https://fully-sole-symposium-nirvana.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,read_shipping,write_products,write_shipping"

[auth]
redirect_urls = ["https://fully-sole-symposium-nirvana.trycloudflare.com/auth/callback", "https://fully-sole-symposium-nirvana.trycloudflare.com/auth/shopify/callback", "https://fully-sole-symposium-nirvana.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
